version: "3.3"

services:
  tracking_server:
    restart: always
    build: ./mlflowdockerfile
    image: mlflow_server
    container_name: mlflow_server
    volumes:
      - ./mlflow:/mlruns
    ports:
      - "${MLFLOW_PORT}:5000"
    networks:
      - mlfow_stack
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlruns/mflow.db
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination file:////mlruns/mlflow-artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:

networks:
  mlfow_stack:
    driver: bridge